### ISSUE TITLE
module input / output with nested modules

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/tfparse#194]
#185 attempted to address this but the solution doesn't work for nested modules

ie. root module contains module a and module b, feeding output of a to b, but module b has a two child modules c and d, that it tries to pass through outputs from module a as inputs to c  and d. currently it appears those inputs in module c and d appear blank.

**Comment by kapilt** [comment]
Previous pr has some additional context

https://github.com/cloud-custodian/tfparse/pull/187

**Comment by ajkerrigan** [comment]
Looks like #195 had some additional changes/fixes/tests to cover this case. Nested modules appear to work as expected now.
