### ISSUE TITLE
pass variables to load_from_path

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/tfparse#27]
alternatively we could try to inject auto variables files into directory.

**Comment by wwitzel3** [comment]
I don't know that I fully understand what we need to do here .. is this for overrides? does the current converter not pickup the auto files now? do you have an example of how you want to use this upstream in c7n-left?

**Comment by kapilt** [comment]
its so a user can specify the correct variable files on the cli if their not in the root module as autoload, and the interpretation can then use those. ie resolving counts/dynamics/for loops to get an accurate list. lotsa of folks use separate var files per env, and then just pass them through on the cli, in this context we want to enable folks to do that via the c7n-left cli.
