### ISSUE TITLE
Document local dev and add some basic scripts for working locally (makefile/justfile/whatever)

### ISSUE THREAD

**Issue by sontek** [cloud-custodian/tfparse#33]
It'd be nice to have some docs on:

1. How to build the go/python to make sure its working
2. How to setup your vscode so that it can debug the go 
3. How to run tests and all that

If we have a makefile that does this it'd be great, but docs are good enough.

**Comment by wwitzel3** [comment]
We don't use just anywhere else in cloud-custodian projects. I don't know how I feel about forcing folks to need yet another tool .. probably just getting some niceties setup in setup.py / pyproject.toml is sufficient.

**Comment by kapilt** [comment]
Makefile is more standard in cloud-custodian, albeit I ❤️ `just` but its hard to justify 😉  since its not a standard tool, its getting close though to easy, one notable gap towards that it still needs to make its way into Debian/ubuntu upstream package universe though.

**Comment by sontek** [comment]
@wwitzel3 Could we document a few more things on this:

1. `tftest` is useful for when you need to attach a debugger to the golang parts
2. Maybe just something about developing in a mix-language environment.    I find it easiest to spin up two vscodes or intellij instances instead of trying to get it all work in one
